[install]
is_configured = 0

[ui]
is_visible = 1
label = SOC Lab Detections

[launcher]
author = nam@cycloneinstruments.ai
description = 10 correlation searches mapped to 12 MITRE ATT&CK techniques
version = 1.0.0
